services:
  db:
    image: mariadb:10.8.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    networks:
      - modulo_network
    env_file:
      - .env
    container_name: modulo-db

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - "./app:/usr/src/app:rw,cached"
      - "/usr/src/app/node_modules"
    stdin_open: true
    environment:
      - CI=true
      - NODE_ENV=development
    ports:
      - "3000:3000"
    restart: always
    networks:
      - modulo_network
    container_name: modulo-app

networks:
  modulo_network:
    driver: bridge
