api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    eager_loading:
        force_eager: false
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

when@prod:
    api_platform:
        enable_swagger: false
        enable_swagger_ui: false
