gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 86400 # 1 day
    single_use: true

    cookie:
        enabled: true
        same_site: lax
        http_only: true
        secure: true
        domain: ".%host_domain%"
