lexik_jwt_authentication:
    secret_key: "%env(resolve:JWT_SECRET_KEY)%"
    public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
    pass_phrase: "%env(JWT_PASSPHRASE)%"
    token_ttl: 86400 # 1 day
    user_identity_field: "uuid"

    # Adds the token in a http only cookie
    set_cookies:
        BEARER:
            httpOnly: true
            samesite: lax
            secure: true
            domain: ".%host_domain%"

    token_extractors:
        authorization_header:
            enabled: false

        cookie:
            enabled: true
            name: BEARER
