liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: gd
    webp:
        generate: true
    controller:
        redirect_response_code: 302

    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        thumbnail_preview_small:
            quality: 90
            filters:
                thumbnail:
                    size: [24, 24]
                    mode: outbound

        thumbnail_preview:
            quality: 80
            filters:
                thumbnail:
                    size: [134, 134]
                    mode: outbound

        thumbnail_preview_large:
            quality: 75
            filters:
                thumbnail:
                    size: [324, 324]
                    mode: outbound

        dashboard_picture_jpeg:
            format: jpeg
            quality: 80

        dashboard_picture_webp:
            format: webp
            quality: 100

        avatar:
            quality: 80
            filters:
                thumbnail:
                    size: [48, 48]
                    mode: outbound

        original:
            quality: 90
