vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        media_image:
            uri_prefix: /media/image
            upload_destination: '%kernel.project_dir%/public/media/image'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y-d-m'
                    date_time_property: uploadTimestamp
        media_file:
            uri_prefix: /media/file
            upload_destination: '%kernel.project_dir%/public/media/file'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y-d-m'
                    date_time_property: uploadTimestamp
