controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: /auth-token
    methods: ["POST"]
    host: api.%host_domain%

api_refresh_token:
    path: /refresh-token
    host: api.%host_domain%

api_token_invalidate:
    path: /invalidate-token
    host: api.%host_domain%

swagger_ui:
    path: /docs
    host: api.%host_domain%
    controller: api_platform.swagger.action.ui
