controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: /api/auth-token
    methods: ["POST"]

api_refresh_token:
    path: /api/refresh-token

api_token_invalidate:
    path: /api/invalidate-token
